### ISSUE TITLE
TamilNadu gpkg

### ISSUE THREAD

**Issue by masabhathini** [sssmartsearch/India_Boundary_Updated#1]
![Capture](https://user-images.githubusercontent.com/25902165/81798238-6f348000-952d-11ea-9ec3-316b0314de2f.JPG)
Hi,
Thanks for the updated boundaries information.

I did not found TamilNadu.gpkg file. Kindly, add that too.......
regards,
M. Sateesh

**Comment by sssmartsearch** [comment]
Dear Sateesh, 
Kindly check the master page where you can find a folder called Tamil Nadu Boundary, inside which the Tamil Nadu boundary is provided as a shapefile. 
Regards,
Suresh

**Comment by masabhathini** [comment]
Yes I agree, Shape file is available in Tamil Nadu Boundary. But, I want stname_TAMIL NADU.gpkg file. Which is an incomplete in `https://github.com/sssmartsearch/India_Boundary_Updated/tree/master/Indian_District_Boundary` directory.

regards,
M. Sateesh
